
<!doctype html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width">
	<title>	
		Intelsius &#8211; A DGP Company | Cold Chain Packaging Solutions	</title>
	
	<!-- Favicon Data -->
			<link rel="shortcut icon" href="http://intelsius.com/wp-content/themes/intelsius_v2/images/favicon/favicon.ico" />
	<!-- <link rel="apple-touch-icon" sizes="57x57" href="http://intelsius.com/wp-content/themes/intelsius_v2/images/apple-touch-icon-57x57.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-touch-icon-57x57.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/images/apple-touch-icon-114x114.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-touch-icon-72x72.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-touch-icon-144x144.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-touch-icon-60x60.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="120x120" href=/images/favicon/apple-touch-icon-120x120.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/images/apple-touch-icon-76x76.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-touch-icon-152x152.png"> -->
<!-- 	<link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon-180x180.png"> -->
<!-- 	<link rel="icon" type="image/png" href="http://intelsius.com/wp-content/themes/intelsius_v2/images/favicon-192x192.png" sizes="192x192"> -->
	<link rel="icon" type="image/png" href="http://intelsius.com/wp-content/themes/intelsius_v2/images/favicon-160x160.png" sizes="160x160">
	<link rel="icon" type="image/png" href="http://intelsius.com/wp-content/themes/intelsius_v2/images/favicon-96x96.png" sizes="96x96">
	<link rel="icon" type="image/png" href="http://intelsius.com/wp-content/themes/intelsius_v2/images/favicon-16x16.png" sizes="16x16">
	<link rel="icon" type="image/png" href="http://intelsius.com/wp-content/themes/intelsius_v2/images/favicon-32x32.png" sizes="32x32">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="http://intelsius.com/wp-content/themes/intelsius_v2/images/mstile-144x144.png">	<!-- End Favicon Data -->
	
	<link rel="profile" href="http://gmpg.org/xfn/11" />
	<!--[if IE 8]><link rel="stylesheet" type="text/css" href="http://intelsius.com/wp-content/themes/intelsius_v2/css/ie8fallback.css"/><![endif]-->
	<link rel="stylesheet" href="<?php echo $this->config->item( 'base_theme_url');?>css/main.css" type="text/css" media="screen" />
	<link rel="pingback" href="http://intelsius.com/xmlrpc.php" />
<!-- 	<link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'> -->
		
	<script src="<?php echo $this->config->item( 'base_theme_url');?>js/modernizr.js"></script>
	<!-- <script src="http://intelsius.com/wp-content/themes/intelsius_v2/js/vendor/jquery.js"></script>				 -->
	<script type="text/javascript" src="<?php echo $this->config->item( 'base_theme_url');?>js/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->config->item( 'base_theme_url');?>js/jquery-migrate-1.2.1.min.js"></script>
    
    <script type="text/javascript" src="<?php echo $this->config->item( 'base_theme_url');?>js/jquery.cycle.all.js"></script>
	<script type="text/javascript" src="<?php echo $this->config->item( 'base_theme_url');?>js/script.js"></script>
	
	<script src="<?php echo $this->config->item( 'base_theme_url');?>js/foundation.min.js"></script>
		

<script type='text/javascript' src='<?php echo $this->config->item( 'base_theme_url');?>js/jquery-migrate.min.js?ver=1.2.1'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://intelsius.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://intelsius.com/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.0.5" />

<!-- Start Of Script Generated By cforms v12.2 [Oliver Seidel | www.deliciousdays.com] -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->config->item( 'base_theme_url');?>css/cforms.css" />
<script type="text/javascript" src="<?php echo $this->config->item( 'base_theme_url');?>js/cforms.js"></script>
<!-- End Of Script Generated By cforms -->

	<style type="text/css">.recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}</style>
	
	<meta name="google-site-verification" content="j-U7V1W0awXNAizJP_3L_DaqfN7p7X1wmvvoLXwISS4" />

</head>
<body>
<!-- LOGOS AND PARTNERS -->
	<header>
		<div class="row">
			<div class="small-12 medium-5 large-5 column">
				<a href="http://intelsius.com"><img src="http://intelsius.com/wp-content/themes/intelsius_v2/images/site-logo.png" alt="Intelsius Logo"></a>
			</div> 
			<div class="small-10 small-centered medium-5 medium-push-2 medium-uncentered large-6 large-uncentered large-push-2 column" id="searchbox">
				<!-- SEARCH FORM -->

				<form role="search" method="get" class="search-form" action="http://intelsius.com/">
					<label>
						<input type="search" class="search-field" placeholder="Search …" value="" name="s" title="Search for:" />
					</label>
					<input type="submit" class="mag op-trans" value="" />
				</form>
				
				<!-- SEARCH FORM -->
			</div>
		</div>
		<div class="row">
			<div class="logos small-8 small-centered small-push-0 medium-4 medium-push-8 medium-uncentered large-4 large-push-8 large-uncentered column">
				
				<img src="http://intelsius.com/wp-content/themes/intelsius_v2/images/iso-logo.png" alt="Certified by ISO">
				<img src="http://intelsius.com/wp-content/themes/intelsius_v2/images/ista-member-logo.png" alt="Member of ISTA">
				<img src="http://intelsius.com/wp-content/themes/intelsius_v2/images/ista-cert-lab-logo.png" alt="Certified by ISTA">
										
			</div>
		</div>			
		
	</header>
<!-- END LOGOS AND PARTNERS -->
	<!-- BEGIN DESKTOP NAVIGATION -->
	
	<div id="menu-main">
		<div class="large-12 column">
			<nav class="row">
			<div class="menu-intelsius-version-2-container"><ul id="menu-intelsius-version-2" class="menu"><li id="menu-item-5374" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-5374"><a href="/"><?php echo $this->lang->line('home'); ?></a></li>
<li id="menu-item-5432" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5432"><a><?php echo $this->lang->line('about us'); ?></a>
<ul class="sub-menu">
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
<!-- 	<li id="menu-item-5434" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5434"><a href="http://intelsius.com/meet-the-team">Meet the Team</a></li> -->
<!-- 	<li id="menu-item-5435" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5435"><a href="http://intelsius.com/academic-partnerships">Academic Partnerships</a></li> -->
<!-- 	<li id="menu-item-5532" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5532"><a href="http://intelsius.com/global-manufacturing">Global Manufacturing</a></li> -->
<!-- 	<li id="menu-item-5436" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5436"><a href="http://intelsius.com/accreditations">Compliance &#038; Certification</a></li> -->
<!-- 	<li id="menu-item-5437" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5437"><a href="http://intelsius.com/corporate-responsibility">Corporate Responsibility</a></li> -->
<!-- 	<li id="menu-item-5438" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5438"><a href="http://intelsius.com/careers">Careers</a></li> -->
</ul>
</li>
<!-- <li id="menu-item-5416" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5416"><a>Markets We Serve</a> -->
<!-- <ul class="sub-menu"> -->
<!-- 	<li id="menu-item-5570" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5570"><a href="http://intelsius.com/diagnostic-reagents">Diagnostic Reagents</a></li> -->
<!-- 	<li id="menu-item-5569" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5569"><a href="http://intelsius.com/pharmaceutical-wholesaler">Pharmaceutical Wholesaler</a></li> -->
<!-- 	<li id="menu-item-5568" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5568"><a href="http://intelsius.com/disease-control">Disease Control</a></li> -->
<!-- 	<li id="menu-item-5567" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5567"><a href="http://intelsius.com/proficiency-testing">Proficiency Testing</a></li> -->
<!-- 	<li id="menu-item-5461" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5461"><a href="http://intelsius.com/human-veterinary-health">Human &#038; Veterinary Health</a></li> -->
<!-- 	<li id="menu-item-5411" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5411"><a href="http://intelsius.com/biopharmaceutical-drugs-devices">Biopharmaceutical Drugs &#038; Devices</a></li> -->
<!-- 	<li id="menu-item-5566" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5566"><a href="http://intelsius.com/laboratories-rd">Laboratories R&#038;D</a></li> -->
<!-- 	<li id="menu-item-5565" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5565"><a href="http://intelsius.com/health-services">Health Services</a></li> -->
<!-- 	<li id="menu-item-5412" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5412"><a href="http://intelsius.com/clinical-trials-couriers">Clinical Trials &#038; Couriers</a></li> -->
<!-- 	<li id="menu-item-5564" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5564"><a href="http://intelsius.com/life-science-tools">Life Science Tools</a></li> -->
<!-- 	<li id="menu-item-5563" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5563"><a href="http://intelsius.com/sample-transport">Sample Transport</a></li> -->
<!-- 	<li id="menu-item-5562" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5562"><a href="http://intelsius.com/food-testing">Food Testing</a></li> -->
<!-- 	<li id="menu-item-5561" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5561"><a href="http://intelsius.com/components">Components</a></li> -->
<!-- 	<li id="menu-item-5560" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5560"><a href="http://intelsius.com/screening">Screening</a></li> -->
<!-- 	<li id="menu-item-5559" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5559"><a href="http://intelsius.com/kitting-fulfilment">Kitting &#038; Fulfilment</a></li> -->
<!-- </ul> -->
<!-- </li> -->
<!-- <li id="menu-item-5420" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5420"><a href="#">Services</a> -->
<!-- <ul class="sub-menu"> -->
<!-- 	<li id="menu-item-5427" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5427"><a href="http://intelsius.com/product">Products</a> -->
<!-- 	<ul class="sub-menu"> -->
<!-- 		<li id="menu-item-5428" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5428"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions">Temperature-Controlled Packaging and Cold Chain Solutions</a> -->
<!-- 		<ul class="sub-menu"> -->
<!-- 			<li id="menu-item-5442" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5442"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/biotherm">BIOTHERM</a></li> -->
<!-- 			<li id="menu-item-5443" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5443"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/pharmatherm">PHARMATHERM</a></li> -->
<!-- 			<li id="menu-item-5624" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5624"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/orca">ORCA</a></li> -->
<!-- 			<li id="menu-item-5445" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5445"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/xtremotherm">XTREMOTHERM</a></li> -->
<!-- 			<li id="menu-item-5446" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5446"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/thermotrek">ThermoTrek™</a></li> -->
<!-- 		</ul> -->
<!-- </li> -->
<!-- 		<li id="menu-item-5421" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5421"><a href="http://intelsius.com/product/regulatory-compliant-packaging">Regulatory Compliant Packaging</a> -->
<!-- 		<ul class="sub-menu"> -->
<!-- 			<li id="menu-item-5422" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5422"><a href="http://intelsius.com/product/regulatory-compliant-packaging/pathoshield">PATHOSHIELD</a></li> -->
<!-- 			<li id="menu-item-5447" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5447"><a href="http://intelsius.com/product/regulatory-compliant-packaging/pathopak">PATHOPAK</a></li> -->
<!-- 			<li id="menu-item-5448" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5448"><a href="http://intelsius.com/product/regulatory-compliant-packaging/bioshield">BIOSHIELD</a></li> -->
<!-- 			<li id="menu-item-5449" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5449"><a href="http://intelsius.com/product/regulatory-compliant-packaging/biomailer">BIOMAILER</a></li> -->
<!-- 			<li id="menu-item-5450" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5450"><a href="http://intelsius.com/product/regulatory-compliant-packaging/biocarrier">BIOCARRIER</a></li> -->
<!-- 		</ul> -->
<!-- </li> -->
<!-- 		<li id="menu-item-5429" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5429"><a href="http://intelsius.com/product/components">Components</a> -->
<!-- 		<ul class="sub-menu"> -->
<!-- 			<li id="menu-item-5451" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5451"><a href="http://intelsius.com/product/components/temperature-loggers">Temperature Loggers</a></li> -->
<!-- 			<li id="menu-item-5452" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5452"><a href="http://intelsius.com/product/components/replacement-outer-cartons">Replacement Outer Cartons</a></li> -->
<!-- 			<li id="menu-item-5453" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5453"><a href="http://intelsius.com/product/components/replacement-eps">Replacement EPS</a></li> -->
<!-- 			<li id="menu-item-5454" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5454"><a href="http://intelsius.com/product/components/pathsorb">PATHSORB</a></li> -->
<!-- 			<li id="menu-item-5456" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5456"><a href="http://intelsius.com/product/components/pathoseal-liquitite">PATHOSEAL LIQUITITE</a></li> -->
<!-- 			<li id="menu-item-5455" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5455"><a href="http://intelsius.com/product/components/pathoseal-95">PATHOSEAL 95</a></li> -->
<!-- 			<li id="menu-item-5457" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5457"><a href="http://intelsius.com/product/components/pathopouch-95kpa">PATHOPOUCH 95kPa</a></li> -->
<!-- 			<li id="menu-item-5458" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5458"><a href="http://intelsius.com/product/components/sample-extraction-utensils">Sample Extraction Utensils</a></li> -->
<!-- 			<li id="menu-item-5459" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5459"><a href="http://intelsius.com/product/components/miscellaneous">Miscellaneous</a></li> -->
<!-- 			<li id="menu-item-5460" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5460"><a href="http://intelsius.com/product/components/thermal-media">Thermal Media</a></li> -->
<!-- 		</ul> -->
<!-- </li> -->
<!-- 	</ul> -->
<!-- </li> -->
<!-- 	<li id="menu-item-5689" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5689"><a href="http://intelsius.com/services/tailored-solutions">Tailored Solutions</a></li> -->
<!-- 	<li id="menu-item-5692" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5692"><a href="http://intelsius.com/services/specialist-transportation-solutions">Specialist Transportation Solutions</a></li> -->
<!-- 	<li id="menu-item-5696" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5696"><a href="http://intelsius.com/services/contingency-planning-and-training">Contingency Planning and Training</a></li> -->
<!-- 	<li id="menu-item-5700" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5700"><a href="http://intelsius.com/services/product-fulfilment-distribution">Product Fulfilment &#038; Distribution</a></li> -->
<!-- 	<li id="menu-item-5439" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5439"><a href="http://intelsius.com/services">Services</a></li> -->
<!-- 	<li id="menu-item-5440" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5440"><a href="http://intelsius.com/technical-services">Technical Services</a></li> -->
<!-- 	<li id="menu-item-5441" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5441"><a href="http://intelsius.com/resources">Resources</a></li> -->
<!-- </ul> -->
<!-- </li> -->
<!-- <li id="menu-item-5464" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5464"><a href="http://intelsius.com/contact-us">Contact Us</a></li> -->

</ul></div>			</nav>
		</div>
	</div>
<!-- END DESKTOP NAVIGATION -->
<!-- MOBILE MENU -->		
			<div class="off-canvas-wrap" data-offcanvas>
		      <div class="inner-wrap">
		   		 <nav class="tab-bar hide-for-large-up" id="menu-mobile">
		     		 <section class="left-small">
		       			 <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
		     		 </section>
		   		 </nav>
						<aside class="left-off-canvas-menu">
						<div class="menu-intelsius-version-2-container"><ul id="menu-intelsius-version-3" class="menu"><li class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-5374"><a href="/"><?php echo $this->lang->line('home'); ?></a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5432"><a><?php echo $this->lang->line('about us'); ?></a>
<ul class="sub-menu">
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>
	<li id="menu-item-5433" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5433"><a href="http://intelsius.com/history"><?php echo $this->lang->line('company history'); ?></a></li>

<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5434"><a href="http://intelsius.com/meet-the-team">Meet the Team</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5435"><a href="http://intelsius.com/academic-partnerships">Academic Partnerships</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5532"><a href="http://intelsius.com/global-manufacturing">Global Manufacturing</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5436"><a href="http://intelsius.com/accreditations">Compliance &#038; Certification</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5437"><a href="http://intelsius.com/corporate-responsibility">Corporate Responsibility</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5438"><a href="http://intelsius.com/careers">Careers</a></li> -->
</ul>
</li>
<!-- <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5416"><a>Markets We Serve</a> -->
<!-- <ul class="sub-menu"> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5570"><a href="http://intelsius.com/diagnostic-reagents">Diagnostic Reagents</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5569"><a href="http://intelsius.com/pharmaceutical-wholesaler">Pharmaceutical Wholesaler</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5568"><a href="http://intelsius.com/disease-control">Disease Control</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5567"><a href="http://intelsius.com/proficiency-testing">Proficiency Testing</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5461"><a href="http://intelsius.com/human-veterinary-health">Human &#038; Veterinary Health</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5411"><a href="http://intelsius.com/biopharmaceutical-drugs-devices">Biopharmaceutical Drugs &#038; Devices</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5566"><a href="http://intelsius.com/laboratories-rd">Laboratories R&#038;D</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5565"><a href="http://intelsius.com/health-services">Health Services</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5412"><a href="http://intelsius.com/clinical-trials-couriers">Clinical Trials &#038; Couriers</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5564"><a href="http://intelsius.com/life-science-tools">Life Science Tools</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5563"><a href="http://intelsius.com/sample-transport">Sample Transport</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5562"><a href="http://intelsius.com/food-testing">Food Testing</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5561"><a href="http://intelsius.com/components">Components</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5560"><a href="http://intelsius.com/screening">Screening</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5559"><a href="http://intelsius.com/kitting-fulfilment">Kitting &#038; Fulfilment</a></li> -->
<!-- </ul> -->
<!-- </li> -->
<!-- <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-5420"><a href="#">Services</a> -->
<!-- <ul class="sub-menu"> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5427"><a href="http://intelsius.com/product">Products</a> -->
<!-- 	<ul class="sub-menu"> -->
<!-- 		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5428"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions">Temperature-Controlled Packaging and Cold Chain Solutions</a> -->
<!-- 		<ul class="sub-menu"> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5442"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/biotherm">BIOTHERM</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5443"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/pharmatherm">PHARMATHERM</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5624"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/orca">ORCA</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5445"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/xtremotherm">XTREMOTHERM</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5446"><a href="http://intelsius.com/temperature-controlled-packaging-and-cold-chain-solutions/thermotrek">ThermoTrek™</a></li> -->
<!-- 		</ul> -->
<!-- </li> -->
<!-- 		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5421"><a href="http://intelsius.com/product/regulatory-compliant-packaging">Regulatory Compliant Packaging</a> -->
<!-- 		<ul class="sub-menu"> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5422"><a href="http://intelsius.com/product/regulatory-compliant-packaging/pathoshield">PATHOSHIELD</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5447"><a href="http://intelsius.com/product/regulatory-compliant-packaging/pathopak">PATHOPAK</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5448"><a href="http://intelsius.com/product/regulatory-compliant-packaging/bioshield">BIOSHIELD</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5449"><a href="http://intelsius.com/product/regulatory-compliant-packaging/biomailer">BIOMAILER</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5450"><a href="http://intelsius.com/product/regulatory-compliant-packaging/biocarrier">BIOCARRIER</a></li> -->
<!-- 		</ul> -->
<!-- </li> -->
<!-- 		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5429"><a href="http://intelsius.com/product/components">Components</a> -->
<!-- 		<ul class="sub-menu"> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5451"><a href="http://intelsius.com/product/components/temperature-loggers">Temperature Loggers</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5452"><a href="http://intelsius.com/product/components/replacement-outer-cartons">Replacement Outer Cartons</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5453"><a href="http://intelsius.com/product/components/replacement-eps">Replacement EPS</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5454"><a href="http://intelsius.com/product/components/pathsorb">PATHSORB</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5456"><a href="http://intelsius.com/product/components/pathoseal-liquitite">PATHOSEAL LIQUITITE</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5455"><a href="http://intelsius.com/product/components/pathoseal-95">PATHOSEAL 95</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5457"><a href="http://intelsius.com/product/components/pathopouch-95kpa">PATHOPOUCH 95kPa</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5458"><a href="http://intelsius.com/product/components/sample-extraction-utensils">Sample Extraction Utensils</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5459"><a href="http://intelsius.com/product/components/miscellaneous">Miscellaneous</a></li> -->
<!-- 			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5460"><a href="http://intelsius.com/product/components/thermal-media">Thermal Media</a></li> -->
<!-- 		</ul> -->
<!-- </li> -->
<!-- 	</ul> -->
<!-- </li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5689"><a href="http://intelsius.com/services/tailored-solutions">Tailored Solutions</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5692"><a href="http://intelsius.com/services/specialist-transportation-solutions">Specialist Transportation Solutions</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5696"><a href="http://intelsius.com/services/contingency-planning-and-training">Contingency Planning and Training</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5700"><a href="http://intelsius.com/services/product-fulfilment-distribution">Product Fulfilment &#038; Distribution</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5439"><a href="http://intelsius.com/services">Services</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5440"><a href="http://intelsius.com/technical-services">Technical Services</a></li> -->
<!-- 	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5441"><a href="http://intelsius.com/resources">Resources</a></li> -->
<!-- </ul> -->
<!-- </li> -->
<!-- <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5464"><a href="http://intelsius.com/contact-us">Contact Us</a></li> -->

</ul>
</div>					</aside>
			<!-- END MOBILE MENU -->
	
